# Generated by Django 5.2.3 on 2025-07-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('vendeur', 'Vendeur'), ('acheteur', 'Acheteur')], max_length=50, null=True),
        ),
    ]
